config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  resources :publications
  root 'articles#index'
  devise_for :users
  resources :comments
  resources :articles
  resources :users, only: %i[index show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/publication.rb
class Publication < ApplicationRecord
  # Adds in the friendlyId into the model
  extend FriendlyId
  # Sets the default find finder to slugged but defaults if not found to default finders like ID
  friendly_id :uuid, use: %i[slugged finders]

  has_many :articles

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /publications
  # GET /publications.json
  def index
    authorize Publication
    @publications = Publication.paginate(page: params[:page], per_page: params[:per_page] ||= 30).order(created_at: :desc)
    respond_to do |format|
      format.json { render json: Publication.all, status: :ok }
      format.html {}
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    respond_to do |format|
      format.json { render json: @publication }
      format.html { @publication }
    end
  end

  # GET /publications/new
  def new
    authorize Publication
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit; end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    authorize @publication

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_publication
    @publication = Publication.friendly.find(params[:id])
    if @publication.present?
      authorize @publication
    end
  end

  # Only allow a list of trusted parameters through.
  def publication_params
    params.require(:publication).permit(:name, :description)
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% publication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>Editing Publication</h1>

    <%= render 'form', publication: @publication %>

    <%= link_to 'Show', @publication %> |
    <%= link_to 'Back', publications_path %>
  </div>
</div>

app/views/publications/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Publications</h1>
        <%= will_paginate @publications %>
      </div>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @publications.each do |publication| %>
            <tr>
              <td><%= publication.name %></td>
              <td><%= publication.description %></td>

              <% if policy(publication).show? %>
                <td><%= link_to 'Show', publication %></td>
              <% end %>
              <% if policy(publication).edit? %>
                <td><%= link_to 'Edit', edit_publication_path(publication) %></td>
              <% end %>
              <% if policy(publication).destroy? %>
                <td><%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="panel-footer">
        <% if policy(Publication).new? %>
          <%= link_to 'New Publication', new_publication_path, class: 'btn btn-success' %>
        <% end %>
        <%= page_entries_info @publications %>
      </div>

    </div>
  </div>
</div>

app/views/publications/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>New Publication</h1>

    <%= render 'form', publication: @publication %>
    <%= link_to 'Back', publications_path %>
  </div>
</div>

app/views/publications/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-success">
      <div class="panel-heading">
        Publication
      </div>

      <div class="panel-body">
        <p>
          <strong>UUID:</strong>
          <%= @publication.uuid %>
        </p>

        <p>
          <strong>Name:</strong>
          <%= @publication.name %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @publication.description %>
        </p>
      </div>

      <div class="panel-footer">
        <% if policy(@publication).edit? %>
          <%= link_to 'Edit', edit_publication_path(@publication), class: "btn btn-success" %>
        <% end %>
        <% if policy(@publication).index? %>
          <%= link_to 'Back', publications_path, class: "btn btn-default" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h1>Articles</h1>
      </div>

      <table class="table table-hover">
        <thead>
        <tr>
          <th>Title</th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @publication.articles.order(created_at: :desc).each do |article| %>
          <tr>
            <td><%= link_to article.title, article.title %></td>
            <% if policy(article).show? %>
              <td><%= link_to 'Show', article %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>